### PR TITLE
Simple lemmatizer

### PR DESCRIPTION
**Pull request by recski**
@juditacs @pajkossy

### CODE REVIEW

**Comment by juditacs** [comment]
Are you aware of the fact that threading makes almost no sense in python because of the GIL: https://wiki.python.org/moin/GlobalInterpreterLock

I'm very much against using threading since it can introduce a lot of bugs and doesn't pay off unless you have something IO intensive.

**Comment by recski** [comment]
I'm not sure I understand everything on this link, but in this case the bottleneck is ocamorph, I'm already getting a 4-5% speed-up by launching several of those.

**Comment by juditacs** [comment]
The gist is that there is no real threading in python. The only thing that can run simultaneously is stuff that does not use the interpreter such as the non-python Ocamorph (or waiting for IO). However, threading can get very complicated and bugs are hard to find, that's why I'm against it unless it is absolutely necessary. How slow is it using a single thread?

**Comment by recski** [comment]
without threads:

```
2015-02-25 13:17:51,142 : simple_lemmatizer (64) - INFO - 0 words done
2015-02-25 14:06:24,953 : simple_lemmatizer (64) - INFO - 41300 words done
2015-02-25 14:06:32,429 : simple_lemmatizer (67) - INFO - done
```

with threads:

```
2015-02-25 12:55:27,155 : simple_lemmatizer (39) - INFO - started 8 threads, <=5174 words each
2015-02-25 13:11:24,314 : simple_lemmatizer (42) - INFO - all threads finished, printing results
```

That's about 49 minutes vs. 16, and there'd be more to gain if I hadn't distributed the data at the beginning: the last 9 minutes of those 6 were actually spent on 1/8th of the data by a single thread that couldn't get CPU time before.

**Pull request merged**
